# Generated by Django 5.0.4 on 2024-05-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict4ddb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmeraudiodutch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='farmeraudioenglish',
            options={'managed': True},
        ),
    ]
