# Generated by Django 5.0.4 on 2024-05-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict4ddb', '0002_alter_farmeraudiodutch_options_and_more'),
    ]

    operations = [
   
    ]
