# Generated by Django 5.0.4 on 2024-05-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict4ddb', '0003_alter_farmeraudiodutch_table_and_more'),
    ]

    operations = [
       

    ]
