# Generated by Django 5.0.4 on 2024-05-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict4ddb', '0005_delete_farmeraudiodutch_delete_farmeraudioenglish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerAudioDutch',
        ),
        migrations.DeleteModel(
            name='FarmerAudioEnglish',
        ),
    ]
