# Generated by Django 5.0.4 on 2024-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict4ddb', '0006_delete_farmeraudiodutch_delete_farmeraudioenglish'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerAudioDutch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('audio_name', models.CharField(blank=True, max_length=15, null=True)),
                ('audio', models.BinaryField(blank=True, null=True)),
                ('seedtype', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'farmer_audio_dutch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FarmerAudioEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('audio_name', models.CharField(blank=True, max_length=15, null=True)),
                ('audio', models.BinaryField(blank=True, null=True)),
                ('seedtype', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'farmer_audio_english',
                'managed': True,
            },
        )
    ]
