# Generated by Django 5.0.4 on 2024-05-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict4ddb', '0007_farmeraudiodutch_farmeraudioenglish_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerAudioEN',
        ),
        migrations.DeleteModel(
            name='FarmerAudioNL',
        ),
    ]
