# Generated by Django 5.0.4 on 2024-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict4ddb', '0008_delete_farmeraudioen_delete_farmeraudionl'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedtype', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('audio_name', models.CharField(blank=True, max_length=15, null=True)),
                ('audio', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audio_dutch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedtype', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('audio_name', models.CharField(blank=True, max_length=15, null=True)),
                ('audio', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audio_english',
                'managed': True,
            },
        ),
    ]
